p8105_hw2_waa2119
================
William Anderson
2022-09-30

``` r
library(tidyverse)
library(dplyr)
library(readxl)
```

# Homework 2

## Problem 1

First we will read in the data about entrance and exits for subway
stations in NYC

We will retain line, station, name, station latitude / longitude, routes
served, entry, vending, entrance type, and ADA compliance then convert
the entry variable from character to a logical variable

``` r
subway_data = 
  read_csv("HW2_Data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%

  janitor::clean_names() %>%
  
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, exit_only, vending, entrance_type, ada) %>%
  
  mutate(entry = recode(entry, "YES" = 1, "NO" = 0))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
subway_data
```

    ## # A tibble: 1,868 × 20
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 1,858 more rows, 10 more variables: route7 <chr>, route8 <dbl>,
    ## #   route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <dbl>, exit_only <chr>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>, and abbreviated variable
    ## #   names ¹​station_name, ²​station_latitude, ³​station_longitude

This data contains information about the different subway lines in New
York City, the locations of their stations and the different routes they
operate on. This data set also has information on whether the entrance
types for the stations, whether the stations contain vendors and whether
they are compliant with the Americans with Disabilities Act.

-   The number of rows in this dataset are 1868 and the number of
    columns are 20

-   The number of distinct stations are 465

``` r
names_and_ada = distinct(subway_data, line, station_name, ada)

ADA_compliant = sum(names_and_ada$ada, na.rm = TRUE)
```

-   The number of ADA compliant stations is 84

-   The proportion of stations without vending that allow entrance is
    given below

``` r
subway_data %>%
  filter(vending != "YES") %>%
  pull(entry) %>%
mean
```

    ## [1] 0.3770492

Now we find the number of stations serving the A train and which of
these are ADA compliant.

``` r
route_number_and_name = distinct(subway_data, station_name, line, ada, across(contains("route")))

A_stations = filter(route_number_and_name, route1 == "A")

A_stations_with_ADA = filter(A_stations, ada == "TRUE")
```

-   The number of stations that serve the A train are 60

-   The number of stations that serve the A train and are ADA compliant
    are 17

## Problem 2

Now we will read in an excel file for Mr. Trash Wheel

``` r
mr_trash_wheel = 
  read_excel("HW2_Data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", skip = 1, na = "", range = cell_cols(1:14)) %>%
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(sports_balls = as.integer(round(sports_balls)))
```

Now we import the professor trash wheel dataset

``` r
prof_trash_wheel = 
  read_excel("HW2_Data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Professor Trash Wheel", skip = 1, na = "") %>%
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(sports_balls = as.integer(round(sports_balls)))
```

Now we combine Mr. Trash Wheel and Professor Trash Wheel datasets

``` r
mr_trash_wheel$dumpster = as.double(mr_trash_wheel$dumpster)

trash_wheel = 
  full_join(mr_trash_wheel, prof_trash_wheel, by = "dumpster")

trash_wheel
```

    ## # A tibble: 453 × 27
    ##    dumpster month.x year.x date.x              weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 May       2014 2014-05-16 00:00:00      4.31      18    1450    1820
    ##  2        2 May       2014 2014-05-16 00:00:00      2.74      13    1120    1030
    ##  3        3 May       2014 2014-05-16 00:00:00      3.45      15    2450    3100
    ##  4        4 May       2014 2014-05-17 00:00:00      3.1       15    2380    2730
    ##  5        5 May       2014 2014-05-17 00:00:00      4.06      18     980     870
    ##  6        6 May       2014 2014-05-20 00:00:00      2.71      13    1430    2140
    ##  7        7 May       2014 2014-05-21 00:00:00      1.91       8     910    1090
    ##  8        8 May       2014 2014-05-28 00:00:00      3.7       16    3580    4310
    ##  9        9 June      2014 2014-06-05 00:00:00      2.52      14    2400    2790
    ## 10       10 June      2014 2014-06-11 00:00:00      3.76      18    1340    1730
    ## # … with 443 more rows, 19 more variables: cigarette_butts.x <dbl>,
    ## #   glass_bottles.x <dbl>, grocery_bags.x <dbl>, chip_bags.x <dbl>,
    ## #   sports_balls.x <int>, homes_powered.x <dbl>, month.y <chr>, year.y <dbl>,
    ## #   date.y <dttm>, weight_tons.y <dbl>, volume_cubic_yards.y <dbl>,
    ## #   plastic_bottles.y <dbl>, polystyrene.y <dbl>, cigarette_butts.y <dbl>,
    ## #   glass_bottles.y <dbl>, grocery_bags.y <dbl>, chip_bags.y <dbl>,
    ## #   sports_balls.y <int>, homes_powered.y <dbl>, and abbreviated variable …

This combined data set contains dumpster data for two different
waterfront trash wheels in Baltimore, Maryland. They are operated by a
company called Healthy Harbor which aims to use these trash wheels to
clean and gather trash floating in the harbor in Baltimore. The combined
dumpsters data set contains 453 observations with key variables
dumpster, month.x, year.x, date.x, weight_tons.x, volume_cubic_yards.x,
plastic_bottles.x, polystyrene.x, cigarette_butts.x, glass_bottles.x,
grocery_bags.x, chip_bags.x, sports_balls.x, homes_powered.x, month.y,
year.y, date.y, weight_tons.y, volume_cubic_yards.y, plastic_bottles.y,
polystyrene.y, cigarette_butts.y, glass_bottles.y, grocery_bags.y,
chip_bags.y, sports_balls.y, homes_powered.y.

-   The total weight of trash collected by Professor Trash Wheel from
    2017 - 2020 was 135.5 tons.

-   The total number of sports balls collected by Mr. Trash Wheel in
    2020 was 856 balls.
